steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/helm-client', '--build-arg', 'HELM_VERSION=v2.14.3', '.']

images: ['gcr.io/$PROJECT_ID/helm-client']
tags: ['cloud-builders-community']
